### PR TITLE
Adds support for official COCO annotation format in source processing

### PR DESCRIPTION
**Pull request by petersen-poul**
I mean, I fully accept that this is probably not merge worthy, but it works, so let me know what needs to be fixed and/or improved :)

### CODE REVIEW

**Comment by petersen-poul** [comment]
Oh, yeah, I totally abused the meaning of --annotations-dir, sorry about that.

bigmler source --annotations-dir=train/_annotations.coco.json --annotations-language=COCO --train train/

**Review by mmerce — CHANGES_REQUESTED** [review]
You need to add a test for that. Tests for VOC and YOLO are in 
bigmler/tests/test_42_composites.py 
 and the test data is in data/images

**Comment by mmerce** [comment]
> Oh, yeah, I totally abused the meaning of --annotations-dir, sorry about that.
> 
> bigmler source --annotations-dir=train/_annotations.coco.json --annotations-language=COCO --train train/

options:
  -h, --help            show this help message and exit
  --HOG                 Whether to use Histogram of Gradients as image
                        analysis features. Captures profiles.
  --add-sources ADD_SOURCES
                        A comma-separated list of source identifiers to add to
                        the composite.
  --annotations-dir ANNOTATIONS_DIR
                        Directory for individual annotation files.
  --annotations-file ANNOTATIONS_FILE
                        File that contains the annotations to images.

**Comment by mmerce** [comment]
Added with checks, tests and examples in version 5.9.0

**Pull request closed without merging**
